# Generated by Django 5.0.1 on 2024-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientsignup',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('ContactNo', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Height', models.IntegerField(blank=True, null=True)),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=200, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
