# Generated by Django 3.0.5 on 2024-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20240321_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietname', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
