# Generated by Django 3.0.5 on 2024-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_dietdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.TimeField()),
                ('meeting_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='dietdetails',
            name='link',
            field=models.TextField(default='nill', max_length=500),
            preserve_default=False,
        ),
    ]
