# Generated by Django 3.0.5 on 2024-04-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20240327_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdetails',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
