# Generated by Django 3.0.5 on 2024-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20240403_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(),
        ),
    ]
