# Generated by Django 3.0.5 on 2024-04-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_meeting_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
    ]
