# Generated by Django 3.0.5 on 2024-04-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_meeting_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
    ]
